/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheorieRouteImport } from './routes/theorie'
import { Route as QuizPanneauxRouteImport } from './routes/quiz-panneaux'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PanneauxRouteImport } from './routes/panneaux'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ExamenRouteImport } from './routes/examen'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin.questions'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'

const TheorieRoute = TheorieRouteImport.update({
  id: '/theorie',
  path: '/theorie',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPanneauxRoute = QuizPanneauxRouteImport.update({
  id: '/quiz-panneaux',
  path: '/quiz-panneaux',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PanneauxRoute = PanneauxRouteImport.update({
  id: '/panneaux',
  path: '/panneaux',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenRoute = ExamenRouteImport.update({
  id: '/examen',
  path: '/examen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/examen': typeof ExamenRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panneaux': typeof PanneauxRoute
  '/quiz': typeof QuizRoute
  '/quiz-panneaux': typeof QuizPanneauxRoute
  '/theorie': typeof TheorieRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/examen': typeof ExamenRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panneaux': typeof PanneauxRoute
  '/quiz': typeof QuizRoute
  '/quiz-panneaux': typeof QuizPanneauxRoute
  '/theorie': typeof TheorieRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/examen': typeof ExamenRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panneaux': typeof PanneauxRoute
  '/quiz': typeof QuizRoute
  '/quiz-panneaux': typeof QuizPanneauxRoute
  '/theorie': typeof TheorieRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/examen'
    | '/mentions-legales'
    | '/panneaux'
    | '/quiz'
    | '/quiz-panneaux'
    | '/theorie'
    | '/admin'
    | '/dashboard'
    | '/profil'
    | '/admin/categories'
    | '/admin/questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/examen'
    | '/mentions-legales'
    | '/panneaux'
    | '/quiz'
    | '/quiz-panneaux'
    | '/theorie'
    | '/admin'
    | '/dashboard'
    | '/profil'
    | '/admin/categories'
    | '/admin/questions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/examen'
    | '/mentions-legales'
    | '/panneaux'
    | '/quiz'
    | '/quiz-panneaux'
    | '/theorie'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profil'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  ExamenRoute: typeof ExamenRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PanneauxRoute: typeof PanneauxRoute
  QuizRoute: typeof QuizRoute
  QuizPanneauxRoute: typeof QuizPanneauxRoute
  TheorieRoute: typeof TheorieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theorie': {
      id: '/theorie'
      path: '/theorie'
      fullPath: '/theorie'
      preLoaderRoute: typeof TheorieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-panneaux': {
      id: '/quiz-panneaux'
      path: '/quiz-panneaux'
      fullPath: '/quiz-panneaux'
      preLoaderRoute: typeof QuizPanneauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panneaux': {
      id: '/panneaux'
      path: '/panneaux'
      fullPath: '/panneaux'
      preLoaderRoute: typeof PanneauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examen': {
      id: '/examen'
      path: '/examen'
      fullPath: '/examen'
      preLoaderRoute: typeof ExamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  ExamenRoute: ExamenRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PanneauxRoute: PanneauxRoute,
  QuizRoute: QuizRoute,
  QuizPanneauxRoute: QuizPanneauxRoute,
  TheorieRoute: TheorieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
